# Generated by Django 5.1.1 on 2024-10-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(default=0, help_text='Enter at least 4 keywords, separated by commas', max_length=255),
            preserve_default=False,
        ),
    ]
