# Generated by Django 5.1.1 on 2024-10-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0002_remove_product_keywords_delete_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ave_ratings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='num_of_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
