# Generated by Django 5.1.1 on 2024-10-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_of_ratings',
            field=models.PositiveIntegerField(),
        ),
    ]
