# Generated by Django 5.1.1 on 2024-10-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0005_alter_productimage_image_url_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url_5',
            field=models.URLField(blank=True, null=True),
        ),
    ]
