# Generated by Django 5.1.1 on 2024-10-15 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0006_alter_productimage_image_url_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ave_ratings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Please provide a rating between 1 and 5.', max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_ratings',
            field=models.PositiveSmallIntegerField(help_text='Please provide a rating between 1 and 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
