# Generated by Django 5.1.1 on 2024-10-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_customuser_date_of_birth_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='card',
        ),
    ]
