# Generated by Django 5.1.1 on 2024-10-31 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_remove_customuser_address_remove_customuser_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item_total',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_total',
            new_name='subtotal',
        ),
        migrations.AddField(
            model_name='address',
            name='address_label',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work')], default='Home', max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('default', 'Default'), ('pickup_address', 'Pickup Address'), ('return_address', 'Return Address')], default='Default', max_length=15),
        ),
        migrations.AddField(
            model_name='address',
            name='barangay',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='specific_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('to_receive', 'To Receive'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('return_refund', 'Return/Refund')], max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status_updates', to='usermanagement.order')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
