# Generated by Django 5.1.1 on 2024-11-02 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+639XXXXXXXXX' or '09XXXXXXXXX'. Exactly 11 digits after the country code or leading zero.", regex='^(?:\\+63|0)\\d{10}$')]),
        ),
    ]
